export const imagesMap: Record<string, any> = {
  "baume_confort_nourrissant_01.png": require("@/assets/images/baume_confort_nourrissant_01.png"),
  "bb_creme_sublimatrice_6_en_1.png": require("@/assets/images/bb_creme_sublimatrice_6_en_1.png"),
  "concentre_bi_phase_recuperateur_01.png": require("@/assets/images/concentre_bi_phase_recuperateur_01.png"),
  "contour_des_yeux_illuminateur_anti_cernes_01.png": require("@/assets/images/contour_des_yeux_illuminateur_anti_cernes_01.png"),
  "creme_anti_rides_repulpante_01.png": require("@/assets/images/creme_anti_rides_repulpante_01.png"),
  "creme_correctrice_sublimatrice_01.png": require("@/assets/images/creme_correctrice_sublimatrice_01.png"),
  "creme_douceur_visage_&_corps_la_gacilly_01.png": require("@/assets/images/creme_douceur_visage_&_corps_la_gacilly_01.png"),
  "demaquillant_express_yeux_pur_bleuet_01.png": require("@/assets/images/demaquillant_express_yeux_pur_bleuet_01.png"),
  "eau_micellaire_lactee_apaisante_01.png": require("@/assets/images/eau_micellaire_lactee_apaisante_01.png"),
  "gel_frais_defatigant_hydratant_01.png": require("@/assets/images/gel_frais_defatigant_hydratant_01.png"),
  "gel_nettoyant_purifiant_01.png": require("@/assets/images/gel_nettoyant_purifiant_01.png"),
  "gel_nettoyant_purifiant_pure_menthe_01.png": require("@/assets/images/gel_nettoyant_purifiant_pure_menthe_01.png"),
  "grand_soin_anti_rides_intense_01.png": require("@/assets/images/grand_soin_anti_rides_intense_01.png"),
  "grand_soin_hydratation_intension_01.png": require("@/assets/images/grand_soin_hydratation_intension_01.png"),
  "grand_soin_regenerant_01.png": require("@/assets/images/grand_soin_regenerant_01.png"),
  "huile_recuperatrice_eclat_nuit_01.png": require("@/assets/images/huile_recuperatrice_eclat_nuit_01.png"),
  "mousse_lactee_nettoyante_illuminatrice_01.png": require("@/assets/images/mousse_lactee_nettoyante_illuminatrice_01.png"),
  "nettoyant_solide_hydratant_01.png": require("@/assets/images/nettoyant_solide_hydratant_01.png"),
  "serum_activateur_eclat_01.png": require("@/assets/images/serum_activateur_eclat_01.png"),
  "serum_anti_perfections_01.png": require("@/assets/images/serum_anti_perfections_01.png"),
};
