import type { Product } from "@/features/diagnostics/types";

// Catalogue local V2. Les produits visage reutilisent les assets de la V1.
// TEMPORARY_DEMO: les produits cheveux/parfum reutilisent des visuels locaux en attendant
// un catalogue valide metier et des packshots dedies.
export const productsCatalog: Product[] = [
  {
    id: "face-hydration-care",
    nom: "Grand Soin Hydratation Intense",
    description:
      "Un soin enveloppant pour aider la peau a retrouver confort, souplesse et hydratation durable.",
    univers: "face",
    categorie: "Soin visage",
    image: "/images/products/grand_soin_hydratation_intension_01.png",
    profilsCompatibles: ["dry_skin", "normal_skin"],
    besoinsCibles: ["hydration", "comfort", "radiance"],
    priorite: 98,
  },
  {
    id: "face-soft-cleanser",
    nom: "Nettoyant Solide Hydratant",
    description:
      "Une base de routine douce pour nettoyer sans accentuer les sensations d'inconfort.",
    univers: "face",
    categorie: "Nettoyant",
    image: "/images/products/nettoyant_solide_hydratant_01.png",
    profilsCompatibles: ["dry_skin", "sensitive_skin"],
    besoinsCibles: ["hydration", "comfort", "sensitivity"],
    priorite: 88,
  },
  {
    id: "face-purifying-gel",
    nom: "Gel Nettoyant Purifiant",
    description:
      "Un geste frais pour aider a purifier la peau et limiter l'exces de brillance.",
    univers: "face",
    categorie: "Nettoyant",
    image: "/images/products/gel_nettoyant_purifiant_01.png",
    profilsCompatibles: ["oily_skin", "combination_skin"],
    besoinsCibles: ["purity", "balance", "imperfections"],
    priorite: 96,
  },
  {
    id: "face-anti-imperfections",
    nom: "Serum Anti-Imperfections",
    description:
      "Un serum cible pour accompagner les peaux sujettes aux imperfections et aux pores visibles.",
    univers: "face",
    categorie: "Serum",
    image: "/images/products/serum_anti_perfections_01.png",
    profilsCompatibles: ["oily_skin", "combination_skin"],
    besoinsCibles: ["imperfections", "purity", "balance"],
    priorite: 92,
  },
  {
    id: "face-radiance-serum",
    nom: "Serum Activateur Eclat",
    description:
      "Une texture legere pour raviver l'eclat et accompagner les peaux en recherche d'uniformite.",
    univers: "face",
    categorie: "Serum",
    image: "/images/products/serum_activateur_eclat_01.png",
    profilsCompatibles: ["normal_skin", "combination_skin"],
    besoinsCibles: ["radiance", "hydration"],
    priorite: 86,
  },
  {
    id: "face-soothing-balm",
    nom: "Baume Confort Nourrissant",
    description:
      "Un soin reconfortant pour les peaux sensibles ou seches en recherche d'apaisement.",
    univers: "face",
    categorie: "Baume",
    image: "/images/products/baume_confort_nourrissant_01.png",
    profilsCompatibles: ["sensitive_skin", "dry_skin"],
    besoinsCibles: ["sensitivity", "comfort", "nutrition"],
    priorite: 94,
  },
  {
    id: "face-night-oil",
    nom: "Huile Recuperatrice Eclat Nuit",
    description:
      "Un soin de nuit sensoriel pour soutenir l'eclat et le confort des peaux en manque de vitalite.",
    univers: "face",
    categorie: "Soin nuit",
    image: "/images/products/huile_recuperatrice_eclat_nuit_01.png",
    profilsCompatibles: ["dry_skin", "combination_skin", "normal_skin"],
    besoinsCibles: ["radiance", "nutrition", "anti_age"],
    priorite: 82,
  },
  {
    id: "face-anti-age-care",
    nom: "Grand Soin Anti-Rides Intense",
    description:
      "Un soin complet pour accompagner les besoins de fermete, de nutrition et de confort.",
    univers: "face",
    categorie: "Soin anti-age",
    image: "/images/products/grand_soin_anti_rides_intense_01.png",
    profilsCompatibles: ["normal_skin", "dry_skin", "sensitive_skin"],
    besoinsCibles: ["anti_age", "nutrition", "comfort"],
    priorite: 84,
  },
  {
    id: "hair-nutrition-mask-demo",
    nom: "Masque Nutrition Intense",
    description:
      "Produit de demonstration pour les longueurs seches en attente du catalogue capillaire valide.",
    univers: "hair",
    categorie: "Masque cheveux",
    image: "/images/products/creme_douceur_visage_&_corps_la_gacilly_01.png",
    profilsCompatibles: ["dry_hair", "curly_hair"],
    besoinsCibles: ["nutrition", "shine", "softness", "curls", "anti_frizz"],
    priorite: 90,
    isTemporaryDemo: true,
  },
  {
    id: "hair-light-shampoo-demo",
    nom: "Shampoing Fraicheur Legere",
    description:
      "Produit de demonstration pour aider a retrouver de la legerete aux racines.",
    univers: "hair",
    categorie: "Shampoing",
    image: "/images/products/gel_nettoyant_purifiant_pure_menthe_01.png",
    profilsCompatibles: ["oily_roots"],
    besoinsCibles: ["freshness", "balance", "volume"],
    priorite: 94,
    isTemporaryDemo: true,
  },
  {
    id: "hair-repair-serum-demo",
    nom: "Serum Reparation Longueurs",
    description:
      "Produit de demonstration pour accompagner les cheveux fragilises et ternes.",
    univers: "hair",
    categorie: "Serum cheveux",
    image: "/images/products/concentre_bi_phase_recuperateur_01.png",
    profilsCompatibles: ["damaged_hair", "dry_hair"],
    besoinsCibles: ["repair", "strength", "heat_protection", "breakage", "shine"],
    priorite: 96,
    isTemporaryDemo: true,
  },
  {
    id: "hair-scalp-comfort-demo",
    nom: "Soin Douceur Cuir Chevelu",
    description:
      "Produit de demonstration pour une routine douce en cas d'inconfort du cuir chevelu.",
    univers: "hair",
    categorie: "Soin cuir chevelu",
    image: "/images/products/eau_micellaire_lactee_apaisante_01.png",
    profilsCompatibles: ["sensitive_scalp"],
    besoinsCibles: ["scalp_comfort", "sensitivity", "comfort"],
    priorite: 92,
    isTemporaryDemo: true,
  },
  {
    id: "fragrance-fresh-demo",
    nom: "Eau Fraiche Citrus",
    description:
      "Produit de demonstration pour les profils frais, petillants et lumineux.",
    univers: "fragrance",
    categorie: "Eau de parfum",
    image: "/images/products/mousse_lactee_nettoyante_illuminatrice_01.png",
    profilsCompatibles: ["fresh"],
    besoinsCibles: ["freshness", "citrus", "light"],
    priorite: 96,
    isTemporaryDemo: true,
  },
  {
    id: "fragrance-floral-demo",
    nom: "Eau Florale Delicate",
    description:
      "Produit de demonstration pour les envies florales, douces et faciles a porter.",
    univers: "fragrance",
    categorie: "Eau de parfum",
    image: "/images/products/contour_des_yeux_illuminateur_anti_cernes_01.png",
    profilsCompatibles: ["floral"],
    besoinsCibles: ["floral", "rose", "magnolia", "softness"],
    priorite: 94,
    isTemporaryDemo: true,
  },
  {
    id: "fragrance-woody-demo",
    nom: "Eau Boisee Chaleureuse",
    description:
      "Produit de demonstration pour les sillages presents, boises et enveloppants.",
    univers: "fragrance",
    categorie: "Eau de parfum",
    image: "/images/products/grand_soin_regenerant_01.png",
    profilsCompatibles: ["woody"],
    besoinsCibles: ["woody", "patchouli", "intensity", "elegance"],
    priorite: 92,
    isTemporaryDemo: true,
  },
  {
    id: "fragrance-gourmand-demo",
    nom: "Eau Gourmande Confort",
    description:
      "Produit de demonstration pour les facettes douces, cocon et reconfortantes.",
    univers: "fragrance",
    categorie: "Eau de parfum",
    image: "/images/products/bb_creme_sublimatrice_6_en_1.png",
    profilsCompatibles: ["amber_gourmand"],
    besoinsCibles: ["amber", "vanilla", "gourmand", "comfort", "intensity"],
    priorite: 90,
    isTemporaryDemo: true,
  },
  {
    id: "fragrance-fruity-demo",
    nom: "Eau Fruitee Peche",
    description:
      "Produit de demonstration pour les envies fruitees, lumineuses et petillantes.",
    univers: "fragrance",
    categorie: "Eau de parfum",
    image: "/images/products/creme_correctrice_sublimatrice_01.png",
    profilsCompatibles: ["fruity"],
    besoinsCibles: ["fruity", "peach", "sparkle", "freshness"],
    priorite: 88,
    isTemporaryDemo: true,
  },
];
